# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Class_info',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('credit', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Depertment',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=2, max_digits=3)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=40)),
                ('room_no', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('year', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Student_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Grades')),
            ],
            options={
                'verbose_name_plural': 'Student_courses',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('pic_status', models.BooleanField(default=False)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Department')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Roles')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teacher_courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('class_count', models.IntegerField(default=0)),
                ('class_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Class_info')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Course')),
            ],
            options={
                'verbose_name_plural': 'Teacher_courses',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('office_location', models.CharField(max_length=45)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Department')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Post')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Roles')),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Timing',
            },
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='teacher_courses',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Teachers'),
        ),
        migrations.AddField(
            model_name='student_courses',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Students'),
        ),
        migrations.AddField(
            model_name='student_courses',
            name='teacher_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Teacher_courses'),
        ),
        migrations.AddField(
            model_name='class_info',
            name='rooms_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Rooms'),
        ),
        migrations.AddField(
            model_name='class_info',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Semester'),
        ),
        migrations.AddField(
            model_name='class_info',
            name='timing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Timing'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Student_courses'),
        ),
        migrations.AddField(
            model_name='admins',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Roles'),
        ),
    ]
